# Generated by Django 5.0.4 on 2024-04-16 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FSCODE', models.CharField(blank=True, max_length=20, null=True)),
                ('Division', models.CharField(blank=True, max_length=10)),
                ('Region', models.CharField(blank=True, max_length=10)),
                ('Head_Quarter', models.CharField(blank=True, max_length=10)),
                ('Design', models.CharField(blank=True, max_length=10)),
                ('EMP_Code', models.CharField(blank=True, max_length=10)),
                ('Reporting_Manager_Name', models.CharField(blank=True, max_length=100)),
                ('Reporting_Manager_Code', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
