# Generated by Django 5.0.4 on 2024-04-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.CharField(blank=True, max_length=10)),
                ('Region', models.CharField(blank=True, max_length=10)),
                ('Head_Quarter', models.CharField(blank=True, max_length=10)),
                ('Category', models.CharField(blank=True, max_length=10)),
                ('Group', models.CharField(blank=True, max_length=10)),
                ('Final_Base_PCPM', models.DecimalField(decimal_places=7, max_digits=17)),
                ('Date', models.DateField()),
            ],
        ),
    ]
