# Generated by Django 5.0.4 on 2024-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_basesales'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthPCPMSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.CharField(blank=True, max_length=10)),
                ('Region', models.CharField(blank=True, max_length=10)),
                ('Head_Quarter', models.CharField(blank=True, max_length=10)),
                ('Secondary_Sales_PCPM', models.DecimalField(decimal_places=0, max_digits=17)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='basesales',
            name='Final_Base_PCPM',
            field=models.DecimalField(decimal_places=0, max_digits=17),
        ),
    ]
